require('../scripts/registerTs.js')
const test = require('node:test')
const assert = require('node:assert')
const { CHROME_BRIDGE_CAPABILITIES } = require('../js/preload/chromeBridgeContract')

test('chrome bridge contract exposes named least-privilege capabilities', function () {
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.bootstrap, ['appVersion', 'developmentMode', 'platform', 'windowId'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.window, ['close', 'maximize', 'minimize', 'setFullScreen', 'unmaximize'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.clipboard, ['readText', 'writeText'])
  assert.ok(CHROME_BRIDGE_CAPABILITIES.views.includes('onEvent'))
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.menu, ['onItemSelected', 'onWillClose', 'open'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.settings, ['onChanged', 'read', 'set'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.session, ['backup', 'read', 'write'])
  assert.ok(CHROME_BRIDGE_CAPABILITIES.downloads.includes('onInfo'))
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.files, ['toFileURL'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.userscripts, ['list', 'onChanged', 'openDirectory', 'unwatch', 'watch'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.passwordManager, ['bitwarden', 'checkTool', 'credentials', 'installTool', 'launchInstaller', 'onePassword', 'prompt', 'readImport'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.prompt, ['cancel', 'complete', 'getStatus', 'onProgress'])
  assert.ok(Object.isFrozen(CHROME_BRIDGE_CAPABILITIES))

  const capabilityNames = Object.keys(CHROME_BRIDGE_CAPABILITIES)
  assert.ok(!capabilityNames.includes('ipc'))
  assert.ok(!capabilityNames.includes('fs'))
  assert.ok(!capabilityNames.includes('electron'))
})
