require('../scripts/registerTs.js')
const test = require('node:test')
const assert = require('node:assert')
const { CHROME_BRIDGE_CAPABILITIES } = require('../js/preload/chromeBridgeContract')

test('chrome bridge contract exposes named least-privilege capabilities', function () {
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.bootstrap, ['appName', 'appVersion', 'developmentMode', 'initialTask', 'initialWindow', 'platform', 'windowId'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.window, ['close', 'maximize', 'minimize', 'setFullScreen', 'unmaximize'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.clipboard, ['readText', 'writeBookmark', 'writeText'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.app, ['addWordToDictionary', 'getHosts', 'onBeforeInputEvent', 'onCommand', 'quit', 'setWindowTitle', 'showFocusModeDialog', 'showSaveDialog', 'showSecondaryMenu', 'updateHandoff', 'writeBookmarksBackup'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.permissions, ['grant', 'onChange'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.tabState, ['onChanges', 'onReadRequest', 'requestSync', 'returnState', 'sendChanges'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.history, ['request'])
  assert.ok(CHROME_BRIDGE_CAPABILITIES.views.includes('onEvent'))
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.menu, ['onItemSelected', 'onWillClose', 'open'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.settings, ['onChanged', 'read', 'set'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.session, ['backup', 'read', 'write'])
  assert.ok(CHROME_BRIDGE_CAPABILITIES.downloads.includes('onInfo'))
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.files, ['toFileURL'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.userscripts, ['list', 'onChanged', 'openDirectory', 'unwatch', 'watch'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.passwordManager, ['bitwarden', 'checkTool', 'credentials', 'installTool', 'launchInstaller', 'onePassword', 'prompt', 'readImport'])
  assert.deepStrictEqual(CHROME_BRIDGE_CAPABILITIES.prompt, ['cancel', 'complete', 'getStatus', 'onProgress'])
  assert.ok(Object.isFrozen(CHROME_BRIDGE_CAPABILITIES))

  const capabilityNames = Object.keys(CHROME_BRIDGE_CAPABILITIES)
  assert.ok(!capabilityNames.includes('ipc'))
  assert.ok(!capabilityNames.includes('fs'))
  assert.ok(!capabilityNames.includes('electron'))
  assert.ok(!capabilityNames.includes('process'))

  // no capability may offer a generic escape hatch
  const methodNames = Object.values(CHROME_BRIDGE_CAPABILITIES).flat()
  assert.ok(!methodNames.includes('send'))
  assert.ok(!methodNames.includes('invoke'))
  assert.ok(!methodNames.includes('require'))
  assert.ok(!methodNames.includes('spawn'))
})
