/*
Exposes the `l()` translation helper to main-process modules.

dist/localization.build.js is generated by scripts/buildLocalization.js (part of
`npm run build`); it bundles the compiled translations together with
localization/localizationHelpers.js, which exports { l } when loaded via require().
*/

const path = require('path')
const { app } = require('electron')

const { l, setLanguageResolver } = require(path.join(__dirname, '../dist/localization.build.js'))

// the helpers read navigator.language in the renderer; the main process has no
// navigator, so it supplies the locale itself rather than the shared file
// reaching for Electron, which would put Electron in the renderer's import graph.
// Resolved lazily because app.getLocale() is only valid once the app is ready.
setLanguageResolver(() => app.getLocale())

module.exports = { l }
