/*
Exposes the `l()` translation helper to main-process modules.

dist/localization.build.js is generated by scripts/buildLocalization.js (part of
`npm run build`); it bundles the compiled translations together with
localization/localizationHelpers.js, which exports { l } when loaded via require().
*/

const path = require('path')

const { l } = require(path.join(__dirname, '../dist/localization.build.js'))

module.exports = { l }
