<#
.SYNOPSIS
Merges the currently checked out feature branch into its base branch without switching branches.

.DESCRIPTION
Detects the base branch the feature branch was created from, then performs a --no-ff merge
in a temporary git worktree so that the main working tree stays on the feature branch.
The merge commit message is generated automatically (no editor is opened).

.EXAMPLE
pwsh .github/maint/merge-feature-branch.ps1

.EXAMPLE
pwsh .github/maint/merge-feature-branch.ps1 -BaseBranch jk-main-2 -Push
#>
[CmdletBinding()]
param(
  # Explicit base branch; detected automatically when omitted.
  [string]$BaseBranch,
  # Branch name patterns considered as merge targets during detection.
  [string[]]$BasePattern = @('main', 'master', 'jk-main*'),
  # Merge commit message; generated by git when omitted.
  [string]$Message,
  # Push the base branch to its upstream after a successful merge.
  [switch]$Push,
  # Report the detected base branch and planned merge without changing anything.
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

function Invoke-Git {
  param([string[]]$Arguments, [switch]$AllowFailure)
  $output = & git $Arguments 2>&1
  if ($LASTEXITCODE -ne 0 -and -not $AllowFailure) {
    throw "git $($Arguments -join ' ') failed:`n$($output -join "`n")"
  }
  return $output
}

function Get-GitValue {
  param([string[]]$Arguments)
  return (Invoke-Git $Arguments | Select-Object -First 1).ToString().Trim()
}

Invoke-Git @('rev-parse', '--is-inside-work-tree') | Out-Null
Set-Location (Get-GitValue @('rev-parse', '--show-toplevel'))

$feature = Get-GitValue @('rev-parse', '--abbrev-ref', 'HEAD')
if ($feature -eq 'HEAD') {
  throw 'HEAD is detached; check out the feature branch first.'
}
if ((Invoke-Git @('status', '--porcelain')) -join '') {
  throw 'Working tree is not clean; commit or stash changes before merging.'
}

function Resolve-BaseBranch {
  $featureTip = Get-GitValue @('rev-parse', 'HEAD')
  $candidates = @()

  foreach ($ref in (Invoke-Git @('for-each-ref', '--format=%(refname:short)', 'refs/heads'))) {
    $branch = $ref.ToString().Trim()
    if (-not $branch -or $branch -eq $feature) { continue }
    if (-not ($BasePattern | Where-Object { $branch -like $_ })) { continue }

    $mergeBase = Invoke-Git @('merge-base', $featureTip, $branch) -AllowFailure
    if ($LASTEXITCODE -ne 0) { continue }
    $mergeBase = ($mergeBase | Select-Object -First 1).ToString().Trim()
    # The feature branch is already contained in this branch.
    if ($mergeBase -eq $featureTip) { continue }

    $candidates += [pscustomobject]@{
      Name      = $branch
      BaseDate  = [long](Get-GitValue @('show', '-s', '--format=%ct', $mergeBase))
      BaseAhead = [int](Get-GitValue @('rev-list', '--count', "$mergeBase..$branch"))
    }
  }

  if (-not $candidates) {
    throw "No unmerged base branch found for '$feature' matching: $($BasePattern -join ', ')"
  }

  # The branch that diverged most recently, preferring the one that moved least since.
  ($candidates | Sort-Object -Property @{Expression = 'BaseDate'; Descending = $true }, 'BaseAhead', 'Name')[0].Name
}

if (-not $BaseBranch) {
  $BaseBranch = Resolve-BaseBranch
}

Write-Host "Merging '$feature' into '$BaseBranch' (--no-ff)."
if ($DryRun) { return }

$worktreePath = Join-Path ([System.IO.Path]::GetTempPath()) ('min-merge-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$mergeArgs = @('-C', $worktreePath, 'merge', '--no-ff', '--no-edit')
if ($Message) { $mergeArgs += @('-m', $Message) }
$mergeArgs += $feature

Invoke-Git @('worktree', 'add', '--quiet', $worktreePath, $BaseBranch) | Out-Null
try {
  $merge = Invoke-Git $mergeArgs -AllowFailure
  if ($LASTEXITCODE -ne 0) {
    Invoke-Git @('-C', $worktreePath, 'merge', '--abort') -AllowFailure | Out-Null
    throw "Merge failed and was aborted:`n$($merge -join "`n")"
  }
  $merge | Write-Host

  if ($Push) {
    Invoke-Git @('-C', $worktreePath, 'push') | Write-Host
  }
} finally {
  Invoke-Git @('worktree', 'remove', '--force', $worktreePath) -AllowFailure | Out-Null
}

Write-Host "Done. Still on '$feature'; '$BaseBranch' is now at $(Get-GitValue @('rev-parse', '--short', $BaseBranch))."
