/* generates the documentation and the per-run agent context digest from the feature ledger */

const fs = require('fs')
const path = require('path')
const ledgerLib = require('./featureLedger')

const docsPath = path.join(ledgerLib.rootDir, 'docs/features.md')
const contextPath = path.join(ledgerLib.rootDir, 'spec/CONTEXT.md')

const GENERATED_NOTICE = '<!-- Generated by scripts/featureDocs.js from spec/FEATURES.json. Do not edit by hand. -->'

function tierSummary (feature) {
  const parts = ledgerLib.TIERS
    .filter((tier) => (feature.tests[tier] || []).length > 0)
    .map((tier) => tier + ' (' + feature.tests[tier].length + ')')
  return parts.length > 0 ? parts.join(', ') : '—'
}

function renderDocs (ledger) {
  const active = ledgerLib.activeFeatures(ledger)
  const retired = ledgerLib.retiredFeatures(ledger)
  const lines = []

  lines.push(GENERATED_NOTICE)
  lines.push('')
  lines.push('# Feature Documentation')
  lines.push('')
  lines.push('The live feature set of the browser, derived from [`spec/FEATURES.json`](../spec/FEATURES.json).')
  lines.push('See [the feature ledger](feature-ledger.md) for how this file is maintained.')
  lines.push('')
  lines.push('## Active features (' + active.length + ')')
  lines.push('')

  active.forEach(function (feature) {
    lines.push('### ' + feature.title)
    lines.push('')
    lines.push(feature.summary)
    lines.push('')
    lines.push('- **id:** `' + feature.id + '`')
    lines.push('- **spec:** [' + feature.specPath + '](../' + feature.specPath + ')')
    lines.push('- **source:** ' + feature.sourceFiles.map((f) => '`' + f + '`').join(', '))
    lines.push('- **tests:** ' + tierSummary(feature))
    if (feature.supersedes.length > 0) {
      lines.push('- **supersedes:** ' + feature.supersedes.map((id) => '`' + id + '`').join(', '))
    }
    lines.push('')
  })

  lines.push('## Retired features (' + retired.length + ')')
  lines.push('')
  lines.push('These are no longer part of the application. Do not reintroduce them without a new specification.')
  lines.push('')
  lines.push('| Feature | Status | Reason |')
  lines.push('| --- | --- | --- |')
  retired.forEach(function (feature) {
    const reason = feature.status === 'removed'
      ? feature.removalReason
      : 'Superseded by `' + feature.supersededBy + '`.'
    lines.push('| ' + feature.title + ' (`' + feature.id + '`) | ' + feature.status + ' | ' + reason + ' |')
  })
  lines.push('')

  return lines.join('\n')
}

function renderContext (ledger) {
  const active = ledgerLib.activeFeatures(ledger)
  const retired = ledgerLib.retiredFeatures(ledger)
  const lines = []

  lines.push(GENERATED_NOTICE)
  lines.push('')
  lines.push('# Feature context for this run')
  lines.push('')
  lines.push('Reuse an existing feature `id` when revising its behaviour instead of creating a second entry for it.')
  lines.push('')
  lines.push('## Active features (' + active.length + ')')
  lines.push('')
  active.forEach(function (feature) {
    lines.push('- `' + feature.id + '` — ' + feature.summary + ' [' + feature.sourceFiles.join(', ') + ']')
  })
  lines.push('')
  lines.push('## Do not reintroduce (' + retired.length + ')')
  lines.push('')
  retired.forEach(function (feature) {
    const reason = feature.status === 'removed'
      ? feature.removalReason
      : 'superseded by `' + feature.supersededBy + '`'
    lines.push('- `' + feature.id + '` — ' + feature.title + ': ' + reason)
  })
  lines.push('')
  lines.push('## Coverage debt')
  lines.push('')
  const untested = active.filter((feature) => ledgerLib.testFilesOf(feature).length === 0)
  if (untested.length === 0) {
    lines.push('- none')
  } else {
    untested.forEach(function (feature) {
      lines.push('- `' + feature.id + '` has no automated tests')
    })
  }
  lines.push('')

  return lines.join('\n')
}

function writeGenerated () {
  const ledger = ledgerLib.loadLedger()
  fs.writeFileSync(docsPath, renderDocs(ledger))
  fs.writeFileSync(contextPath, renderContext(ledger))
}

module.exports = { docsPath, contextPath, renderDocs, renderContext, writeGenerated }

if (require.main === module) {
  writeGenerated()
  console.log('Wrote docs/features.md and spec/CONTEXT.md')
}
